version: '3.9'


services:
  config-service:
    image: bcf23surokkha/config-service
    environment:
      - CLOUD_CONFIG_GITHUB_TOKEN
    networks:
      - surokkha
    deploy:
      replicas: 1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8078/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s


networks:
  surokkha:
